// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBP3EVdVrtgEE3bmY_gxUG2eM-90UmnXA',
    appId: '1:418495054166:web:1350d0a87bc9012063d6f7',
    messagingSenderId: '418495054166',
    projectId: 'loginfb-69ed7',
    authDomain: 'loginfb-69ed7.firebaseapp.com',
    storageBucket: 'loginfb-69ed7.firebasestorage.app',
    measurementId: 'G-Y2R9JFKYDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2uOL_H5xv3g0exHg6nh9BSI34hVth2N4',
    appId: '1:418495054166:android:445f9e16be1df52063d6f7',
    messagingSenderId: '418495054166',
    projectId: 'loginfb-69ed7',
    storageBucket: 'loginfb-69ed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSdjrqbzn1s-jUY9A0Rl0QhYhkjIkfScc',
    appId: '1:418495054166:ios:2f99916dc8ec8f3963d6f7',
    messagingSenderId: '418495054166',
    projectId: 'loginfb-69ed7',
    storageBucket: 'loginfb-69ed7.firebasestorage.app',
    iosBundleId: 'com.example.implementacionFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSdjrqbzn1s-jUY9A0Rl0QhYhkjIkfScc',
    appId: '1:418495054166:ios:2f99916dc8ec8f3963d6f7',
    messagingSenderId: '418495054166',
    projectId: 'loginfb-69ed7',
    storageBucket: 'loginfb-69ed7.firebasestorage.app',
    iosBundleId: 'com.example.implementacionFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBP3EVdVrtgEE3bmY_gxUG2eM-90UmnXA',
    appId: '1:418495054166:web:194b2fdb5917b42963d6f7',
    messagingSenderId: '418495054166',
    projectId: 'loginfb-69ed7',
    authDomain: 'loginfb-69ed7.firebaseapp.com',
    storageBucket: 'loginfb-69ed7.firebasestorage.app',
    measurementId: 'G-X3NJ7P3PRF',
  );

}